[profile.default]
src = "src"
out = "out"
libs = ['lib']
remappings = [
    '@chainlink/contracts-ccip/=lib/ccip/contracts/', "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/", "@openzeppelin/=lib/openzeppelin-contracts"
]

[rpc_endpoints]
ethereumSepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"
avalancheFuji = "${AVALANCHE_FUJI_RPC_URL}"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
